# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Rock Bottom' do
	pod 'SwiftHTTP', '~> 0.9.4'
	pod 'SwiftyJSON', '~> 2.2.0'
end

target 'Rock BottomTests' do

end

